"""empty message

Revision ID: b664f75ee3d7
Revises: 
Create Date: 2021-11-02 15:49:05.945189

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b664f75ee3d7'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('category', 'name',
               existing_type=sa.TEXT(length=40),
               nullable=False)
    op.alter_column('category', 'type',
               existing_type=sa.TEXT(length=20),
               nullable=False)
    op.alter_column('failure', 'notes',
               existing_type=sa.TEXT(length=1024),
               nullable=False)
    op.add_column('repair', sa.Column('failure_id', sa.Integer(), nullable=True))
    op.drop_constraint(None, 'repair', type_='foreignkey')
    op.create_foreign_key(None, 'repair', 'failure', ['failure_id'], ['id'])
    op.drop_column('repair', 'category_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('repair', sa.Column('category_id', sa.INTEGER(), nullable=True))
    op.drop_constraint(None, 'repair', type_='foreignkey')
    op.create_foreign_key(None, 'repair', 'failure', ['category_id'], ['id'])
    op.drop_column('repair', 'failure_id')
    op.alter_column('failure', 'notes',
               existing_type=sa.TEXT(length=1024),
               nullable=True)
    op.alter_column('category', 'type',
               existing_type=sa.TEXT(length=20),
               nullable=True)
    op.alter_column('category', 'name',
               existing_type=sa.TEXT(length=40),
               nullable=True)
    # ### end Alembic commands ###
